/**
 * HTML Exporter
 *
 * Exports competition results to a printable HTML report.
 */

import * as fs from "fs";
import type { Competition } from "../types/competition";
import type { CompetitionResult, TaskResult } from "../types/results";
import type { Participant } from "../types/participant";

/**
 * HTML export options
 */
export interface HtmlExportOptions {
  /** Output file path */
  outputPath: string;

  /** Include task results */
  includeTaskResults: boolean;

  /** Include standings */
  includeStandings: boolean;

  /** Decimal places for points */
  decimals?: number;
}

/**
 * Export competition results to HTML file
 */
export async function exportToHtml(
  competition: Competition,
  competitionResult: CompetitionResult,
  taskResults: TaskResult[],
  options: HtmlExportOptions
): Promise<string> {
  const participantMap = new Map<number, Participant>();
  for (const p of competition.participants) {
    participantMap.set(p.id, p);
  }

  const taskNameMap = new Map<string, string>();
  for (const t of competition.tasks) {
    taskNameMap.set(t.id, t.name);
  }

  const decimals = options.decimals ?? 1;

  const html = generateHtml(
    competition,
    competitionResult,
    taskResults,
    participantMap,
    taskNameMap,
    options.includeStandings,
    options.includeTaskResults,
    decimals
  );

  await fs.promises.writeFile(options.outputPath, html, "utf-8");
  return options.outputPath;
}

/**
 * Generate full HTML document
 */
function generateHtml(
  competition: Competition,
  competitionResult: CompetitionResult,
  taskResults: TaskResult[],
  participantMap: Map<number, Participant>,
  taskNameMap: Map<string, string>,
  includeStandings: boolean,
  includeTaskResults: boolean,
  decimals: number
): string {
  const sections: string[] = [];

  // Competition header
  sections.push(`
    <header class="competition-header">
      <h1>${escapeHtml(competition.name)}</h1>
      <p class="location">${escapeHtml(competition.location)}</p>
      <p class="dates">${formatDateRange(competition.startDate, competition.endDate)}</p>
      <p class="meta">
        ${competition.participants.length} pilots &bull;
        ${taskResults.length} tasks scored &bull;
        ${competition.formula.name}
      </p>
    </header>
  `);

  // Standings section
  if (includeStandings) {
    sections.push(
      generateStandingsHtml(
        competitionResult,
        taskResults,
        participantMap,
        taskNameMap,
        decimals
      )
    );
  }

  // Task results sections
  if (includeTaskResults) {
    for (const taskResult of taskResults) {
      sections.push(
        generateTaskResultHtml(taskResult, participantMap, decimals)
      );
    }
  }

  // Wrap in full document
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(competition.name)} - Results</title>
  <style>
    ${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    ${sections.join("\n")}
    <footer>
      <p>Generated by Trackdownloader on ${new Date().toLocaleDateString()}</p>
    </footer>
  </div>
</body>
</html>`;
}

/**
 * Generate standings HTML table
 */
function generateStandingsHtml(
  competitionResult: CompetitionResult,
  taskResults: TaskResult[],
  participantMap: Map<number, Participant>,
  taskNameMap: Map<string, string>,
  decimals: number
): string {
  const taskIds = taskResults.map((t) => t.taskId);

  // Build header row
  const taskHeaders = taskIds
    .map((id) => {
      const name = taskNameMap.get(id) || id;
      return `<th class="task-col">${escapeHtml(name)}</th>`;
    })
    .join("");

  // Build data rows
  const rows = competitionResult.standings
    .map((standing) => {
      const participant = participantMap.get(standing.participantId);
      const gender =
        participant?.genre === "MALE"
          ? "M"
          : participant?.genre === "FEMALE"
            ? "F"
            : "";
      const taskCells = taskIds
        .map((taskId) => {
          const score = standing.taskScores[taskId];
          const countingPts = score?.countingPoints ?? 0;
          const originalPts = score?.originalPoints ?? 0;
          const isPartial = originalPts !== countingPts && originalPts > 0;

          if (isPartial) {
            return `<td class="points">${formatPoints(countingPts, decimals)}/<del>${formatPoints(originalPts, decimals)}</del></td>`;
          }
          return `<td class="points">${formatPoints(countingPts, decimals)}</td>`;
        })
        .join("");

      return `
        <tr>
          <td class="rank">${standing.rank}</td>
          <td class="id">${standing.participantId}</td>
          <td class="pilot">${escapeHtml(participant?.name || `Pilot ${standing.participantId}`)}</td>
          <td class="gender">${gender}</td>
          <td class="nation">${escapeHtml(participant?.nation || "")}</td>
          <td class="glider">${escapeHtml(participant?.glider || "")}</td>
          <td class="category">${escapeHtml(participant?.gliderClass || "")}</td>
          ${taskCells}
          <td class="total">${formatPoints(standing.totalPoints, 0)}</td>
        </tr>
      `;
    })
    .join("");

  return `
    <section class="standings">
      <h2>Overall Standings</h2>
      <table class="results-table">
        <thead>
          <tr>
            <th class="rank-col">#</th>
            <th class="id-col">ID</th>
            <th class="pilot-col">Pilot</th>
            <th class="gender-col">M/F</th>
            <th class="nation-col">Nation</th>
            <th class="glider-col">Glider</th>
            <th class="category-col">Category</th>
            ${taskHeaders}
            <th class="total-col">Total</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Generate task result HTML table
 */
function generateTaskResultHtml(
  taskResult: TaskResult,
  participantMap: Map<number, Participant>,
  decimals: number
): string {
  const sortedResults = [...taskResult.pilotResults].sort(
    (a, b) => a.rank - b.rank
  );

  const rows = sortedResults
    .map((result) => {
      const participant = participantMap.get(result.pilotId);
      const goalClass = result.reachedGoal ? "in-goal" : "";

      return `
        <tr class="${goalClass}">
          <td class="rank">${result.rank}</td>
          <td class="pilot">${escapeHtml(participant?.name || `Pilot ${result.pilotId}`)}</td>
          <td class="nation">${escapeHtml(participant?.nation || "")}</td>
          <td class="distance">${formatDistance(result.distance)}</td>
          <td class="time">${formatTime(result.time)}</td>
          <td class="points">${formatPoints(result.distancePoints, decimals)}</td>
          <td class="points">${formatPoints(result.timePoints, decimals)}</td>
          <td class="points">${formatPoints(result.leadingPoints, decimals)}</td>
          <td class="penalty">${result.penaltyPoints > 0 ? `-${formatPoints(result.penaltyPoints, decimals)}` : ""}</td>
          <td class="total">${formatPoints(result.totalPoints, decimals)}</td>
        </tr>
      `;
    })
    .join("");

  return `
    <section class="task-result">
      <h2>${escapeHtml(taskResult.taskName)}</h2>
      <p class="task-date">${taskResult.taskDate}</p>

      <div class="task-stats">
        <span class="stat">
          <strong>Day Quality:</strong> ${(taskResult.dayQuality * 100).toFixed(1)}%
        </span>
        <span class="stat">
          <strong>In Goal:</strong> ${taskResult.statistics.pilotsInGoal}/${taskResult.statistics.pilotsFlying}
        </span>
        <span class="stat">
          <strong>Best Distance:</strong> ${formatDistance(taskResult.statistics.bestDistance)} km
        </span>
        ${
          taskResult.statistics.bestTime > 0
            ? `
          <span class="stat">
            <strong>Best Time:</strong> ${formatTime(taskResult.statistics.bestTime)}
          </span>
        `
            : ""
        }
      </div>

      <table class="results-table">
        <thead>
          <tr>
            <th class="rank-col">#</th>
            <th class="pilot-col">Pilot</th>
            <th class="nation-col">Nation</th>
            <th>Distance</th>
            <th>Time</th>
            <th>Dist Pts</th>
            <th>Time Pts</th>
            <th>Lead Pts</th>
            <th>Penalty</th>
            <th class="total-col">Total</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </section>
  `;
}

/**
 * Get CSS styles for the HTML report
 */
function getStyles(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 12px;
      line-height: 1.4;
      color: #333;
      background: #fff;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    .competition-header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #333;
    }

    .competition-header h1 {
      font-size: 24px;
      margin-bottom: 5px;
    }

    .competition-header .location {
      font-size: 16px;
      color: #666;
    }

    .competition-header .dates {
      font-size: 14px;
      color: #666;
    }

    .competition-header .meta {
      margin-top: 10px;
      font-size: 12px;
      color: #888;
    }

    section {
      margin-bottom: 40px;
    }

    h2 {
      font-size: 18px;
      margin-bottom: 10px;
      padding-bottom: 5px;
      border-bottom: 1px solid #ddd;
    }

    .task-date {
      color: #666;
      margin-bottom: 10px;
    }

    .task-stats {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
      margin-bottom: 15px;
      padding: 10px;
      background: #f5f5f5;
      border-radius: 4px;
    }

    .stat {
      font-size: 12px;
    }

    .results-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 11px;
    }

    .results-table th,
    .results-table td {
      padding: 6px 8px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    .results-table th {
      background: #f0f0f0;
      font-weight: 600;
      white-space: nowrap;
    }

    .results-table tbody tr:hover {
      background: #f9f9f9;
    }

    .rank-col { width: 40px; text-align: center; }
    .pilot-col { min-width: 150px; }
    .nation-col { width: 50px; text-align: center; }
    .glider-col { min-width: 100px; }
    .task-col { width: 60px; text-align: right; }
    .total-col { width: 70px; text-align: right; font-weight: 600; }

    .rank { text-align: center; }
    .nation { text-align: center; }
    .distance, .time, .points, .penalty, .total { text-align: right; }
    .total { font-weight: 600; }

    .discarded {
      color: #999;
      text-decoration: line-through;
    }

    .in-goal {
      background: #e8f5e9;
    }

    footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 10px;
      color: #888;
    }

    @media print {
      body { font-size: 10px; }
      .container { padding: 10px; }
      section { page-break-inside: avoid; }
      .results-table { font-size: 9px; }
    }
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Format date range
 */
function formatDateRange(start: string, end: string): string {
  const startDate = new Date(start);
  const endDate = new Date(end);

  const options: Intl.DateTimeFormatOptions = {
    month: "short",
    day: "numeric",
    year: "numeric",
  };

  if (start === end) {
    return startDate.toLocaleDateString("en-US", options);
  }

  return `${startDate.toLocaleDateString("en-US", options)} - ${endDate.toLocaleDateString("en-US", options)}`;
}

/**
 * Format distance in km
 */
function formatDistance(meters: number): string {
  return (meters / 1000).toFixed(2);
}

/**
 * Format time as HH:MM:SS
 */
function formatTime(seconds: number | null): string {
  if (seconds === null || seconds <= 0) return "-";

  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
  }
  return `${minutes}:${String(secs).padStart(2, "0")}`;
}

/**
 * Format points with decimal places
 */
function formatPoints(points: number, decimals: number): string {
  return points.toFixed(decimals);
}

/**
 * Generate HTML string (for preview without saving)
 */
export function generateHtmlPreview(
  competition: Competition,
  competitionResult: CompetitionResult,
  taskResults: TaskResult[],
  includeStandings: boolean,
  includeTaskResults: boolean
): string {
  const participantMap = new Map<number, Participant>();
  for (const p of competition.participants) {
    participantMap.set(p.id, p);
  }

  const taskNameMap = new Map<string, string>();
  for (const t of competition.tasks) {
    taskNameMap.set(t.id, t.name);
  }

  return generateHtml(
    competition,
    competitionResult,
    taskResults,
    participantMap,
    taskNameMap,
    includeStandings,
    includeTaskResults,
    1
  );
}
